// Box2D v3 compiled as a single translation unit, for platforms without a system libbox2d (see box2d.v).
// The sources come from thirdparty/box2d (git tag v3.1.1), fetched by `velo deps`.
// Guarded: V can emit a #include more than once.
#ifndef VELO_BOX2D_SOURCE_C
#define VELO_BOX2D_SOURCE_C
#include "../thirdparty/box2d/src/aabb.c"
#include "../thirdparty/box2d/src/arena_allocator.c"
#include "../thirdparty/box2d/src/array.c"
#include "../thirdparty/box2d/src/bitset.c"
#include "../thirdparty/box2d/src/body.c"
#include "../thirdparty/box2d/src/broad_phase.c"
#include "../thirdparty/box2d/src/constraint_graph.c"
#include "../thirdparty/box2d/src/contact.c"
#include "../thirdparty/box2d/src/contact_solver.c"
#include "../thirdparty/box2d/src/core.c"
#include "../thirdparty/box2d/src/distance.c"
#include "../thirdparty/box2d/src/distance_joint.c"
#include "../thirdparty/box2d/src/dynamic_tree.c"
#include "../thirdparty/box2d/src/geometry.c"
#include "../thirdparty/box2d/src/hull.c"
#include "../thirdparty/box2d/src/id_pool.c"
#include "../thirdparty/box2d/src/island.c"
#include "../thirdparty/box2d/src/joint.c"
#include "../thirdparty/box2d/src/manifold.c"
#include "../thirdparty/box2d/src/math_functions.c"
#include "../thirdparty/box2d/src/motor_joint.c"
#include "../thirdparty/box2d/src/mouse_joint.c"
#include "../thirdparty/box2d/src/mover.c"
#include "../thirdparty/box2d/src/prismatic_joint.c"
#include "../thirdparty/box2d/src/revolute_joint.c"
#include "../thirdparty/box2d/src/sensor.c"
#include "../thirdparty/box2d/src/shape.c"
#include "../thirdparty/box2d/src/solver.c"
#include "../thirdparty/box2d/src/solver_set.c"
#include "../thirdparty/box2d/src/table.c"
#include "../thirdparty/box2d/src/timer.c"
#include "../thirdparty/box2d/src/types.c"
#include "../thirdparty/box2d/src/weld_joint.c"
#include "../thirdparty/box2d/src/wheel_joint.c"
#include "../thirdparty/box2d/src/world.c"
#endif
