module main

// v2js — translates a Velo game written in V into JavaScript for the WebGL runtime (webgl/runtime).
//
//   v2js <project dir> -o <output dir> [-d <flag>]...
//
// The V compiler's own parser and type checker read the game (and the engine and vlib, for the types), with
// `-d webgl` defined, so `$if webgl ? { }` selects web-only code. Every module of the game (the files inside
// the project directory) becomes one ES module, `<module>.js`; engine and vlib calls go to the runtime
// (`import { core, render, ... } from 'velo-runtime'`, which a bundler resolves to webgl/runtime/index.ts).
// `entry.js` boots the runtime and calls the game's main(). `velo build webgl` runs this, then esbuild.
import os
import v.ast
import v.pref
import v.builder

const usage = 'usage: v2js <project dir> -o <output dir> [-d <flag>]...'

fn main() {
	mut dir := ''
	mut out_dir := ''
	mut defines := ['webgl']
	args := os.args[1..]
	mut i := 0
	for i < args.len {
		a := args[i]
		match a {
			'-o' {
				i++
				out_dir = args[i] or { fail(usage) }
			}
			'-d' {
				i++
				defines << args[i] or { fail(usage) }
			}
			'-h', '--help' {
				println(usage)
				exit(0)
			}
			else {
				if a.starts_with('-') {
					fail('unknown option "${a}"\n${usage}')
				}
				dir = a
			}
		}

		i++
	}
	if dir == '' || out_dir == '' {
		fail(usage)
	}
	project_dir := os.real_path(dir)
	if !os.is_dir(project_dir) {
		fail('"${dir}" is not a directory')
	}
	home := velo_home()
	vexe := os.real_path(os.find_abs_path_of_executable('v') or { fail('`v` not found on PATH') })
	os.setenv('VEXE', vexe, true)
	vpath := '@vlib|${os.dir(home)}|@vmodules'
	mut vargs := ['-path', vpath, '-check', '-os', 'wasm32_emscripten', '-gc', 'none']
	for d in defines {
		vargs << ['-d', d]
	}
	vargs << project_dir
	mut prefs, _ := pref.parse_args([], vargs)
	mut b := builder.new_builder(prefs)
	mut files := b.get_builtin_files()
	files << b.get_user_files()
	b.set_module_lookup_paths()
	b.front_and_middle_stages(files) or {
		if !err.msg().contains('stop_after_checker') {
			fail('V check failed: ${err}')
		}
	}
	if b.parsed_files.any(it.errors.len > 0) {
		fail('the game has V errors, fix them first (`v -check .`)')
	}
	by_mod := module_files(b.parsed_files, project_dir)
	if 'main' !in by_mod {
		fail('no `module main` found in ${project_dir}')
	}
	mut mods := by_mod.keys()
	mods.sort()
	os.mkdir_all(out_dir) or { fail(err.msg()) }
	mut g := new_gen(b.table, project_dir, mods)
	for mod in mods {
		js := g.gen_module(mod, by_mod[mod] or { []&ast.File{} })
		os.write_file(os.join_path(out_dir, '${mod}.js'), js) or { fail(err.msg()) }
	}
	os.write_file(os.join_path(out_dir, 'entry.js'), entry_js) or { fail(err.msg()) }
	for w in g.warnings {
		eprintln('v2js: warning: ${w}')
	}
	if g.errors.len > 0 {
		for e in g.errors {
			eprintln('v2js: error: ${e}')
		}
		exit(1)
	}
	println('v2js: ${mods.len} module(s) -> ${out_dir}')
}

const entry_js = "// Generated by tools/v2js — do not edit.
import { app } from 'velo-runtime'
import { main } from './main.js'

app.boot(main)
"

// velo_home: the engine directory (the repo this tool lives in), overridable with VELO_HOME.
fn velo_home() string {
	home := os.real_path(os.getenv_opt('VELO_HOME') or { @VMODROOT })
	if !os.is_file(os.join_path(home, 'core', 'node.v')) {
		fail('engine not found in "${home}" — set VELO_HOME to the Velo repo directory')
	}
	return home
}

@[noreturn]
fn fail(msg string) {
	eprintln('v2js: ${msg}')
	exit(1)
}
